### ISSUE TITLE
is_distance = TRUE experimental ?

### ISSUE THREAD

**Issue by hovestadt** [jkrijthe/Rtsne#11]
in the man page it says supplying a precomputed distance matrix is experimental, could you comment on that? is it safe to use? thanks!

**Comment by jkrijthe** [comment]
It is flagged as experimental because I added this functionality myself (it was not part of the underlying C++ code this package is the wrapper for), and it has not been thoroughly tested. For instance: providing the Euclidean distance matrix directly does not converge to the same tsne map as having the C++ code calculate the euclidean distance itself. Having said that, I and others have found it useful to use different distance measures and these seem to give sensible results. If you run into any problem please let me know.

**Comment by jkrijthe** [comment]
The experimental flag is removed in  14b195fe09a1cbc2b787d3ee74d0b0bbe066f2e6
