### ISSUE TITLE
Reproducing R results in "pure" C++

### ISSUE THREAD

**Issue by NikTuzov** [jkrijthe/Rtsne#18]
Hello Jesse:

Is there a way to reproduce R results just in C++? The other repository:

https://github.com/lvdmaaten/bhtsne

has been updated recently as well, but I can see that the TSNE::run() function has 11 parameters there and 19 parameters in your repository. I tried downloading your C++ files but, contrary to Maaten's files, I can't compile them. If there is a way to compile your C++ files or to reproduce R results with Maaten's files, please let me know.

Regards,
Nik

**Comment by jkrijthe** [comment]
Dear Nik,

The package is based on an earlier version of Van der Maaten's files, and while I think I kept up with most of the changes, it contains some other features as well that were not originally present in Van der Maaten's code. The main reason for the difference in the number of parameters for run(), however, is due to the ability to set the values of several variables that are constants in Van de Maaten's files. There are some other minor differences, which could lead to quantitative differences when running the two versions, although I would hope and expect that the qualitative outcomes are very similar. In short: there is no guarantee that the code in my package will reproduce exactly the results of the code in Van der Maaten's repository.

Compiling the code is quite straightforward, for instance, from RStudio, when the Rcpp package is installed. But if you really want to obtain the exact results from Van der Maaten's code in R, I guess the easiest way is to just compile and run his binary and load the results into R.

Hope this helps.

Best,
Jesse

**Comment by NikTuzov** [comment]
Hello Jesse:

Thank you for replying. My intention was to compile the C++ source files with a compiler like g++ and get the same numerical results as in Rtsne package. That C++ code is going to be used in a standalone C++ application that has no ties to R or RStudio. Still, it would be nice to be able to say that the application's results can be reproduced in R. The problem is somewhat similar to what is posted here:

http://stackoverflow.com/questions/23304012/using-rcpp-headers-in-c

but I don't understand the proposed solution(s).

**Comment by jkrijthe** [comment]
I see. I'm sorry I have no advise to offer here, as I have never attempted to do anything like that. Good luck!
