### ISSUE TITLE
Seg fault problem

### ISSUE THREAD

**Issue by dweemx** [jkrijthe/Rtsne#21]
When I run multiple Rtsne in paralell, I got this error:

`An irrecoverable exception occurred. R is aborting now ...

 *** caught segfault ***
address 0x1a1, cause 'memory not mapped'

Traceback:
 1: .Call("Rtsne_Rtsne_cpp", PACKAGE = "Rtsne", X, no_dims_in, perplexity_in,     theta_in, verbose, max_iter, distance_precomputed, Y_in,     init, stop_lying_iter_in, mom_switch_iter_in, momentum_in,     final_momentum_in, eta_in, exaggeration_factor_in)
`
I have already reinstalled R and all packages

I really don't understand where the problem is coming from...

**Comment by jkrijthe** [comment]
Do you have a small script that reproduces the problem?

**Comment by maxdy** [comment]
initial.dims.grid<-c(2,5,10,15,20,25,30,35,40,45,50)
  perplexity.grid<-c(5,15,25,30,40,50,60,75,100)

  doParallel::registerDoParallel(); 
  options(cores=length(initial.dims.grid))
  print(paste("Using", foreach::getDoParWorkers(), "cores."))
  
  for(perp in perplexity.grid) {
    foreach(i=1:length(initial.dims.grid)) %dorng% {
        [...]
        tsne.res<- Rtsne(t((mat)), initial_dims=initial.dims.grid[i], perplexity=perp)
      }
    }
  }

Not really, but what is weird is that the script work on RStudio but when I run it using RScript command it gives me Segmentation fault (core dumped); So I don't think it's the Rtsne code itself

Any idea?

**Comment by jkrijthe** [comment]
I'm afraid, the example is not specific enough for me to reproduce it. Can you reproduce it with synthetic data? Does it only occur for large datasets (larger than RAM) or also for smaller datasets?

**Comment by maxdy** [comment]
I think it's a RAM issue (works for smaller datasets); but I still don't understand why it works (for larger datasets) in RStudio and not using the command line (Rscript)?

**Comment by jkrijthe** [comment]
I do not currently know what is causing this. Perhaps debugging with valgrind could help? Anyway, I will leave the issue open for now, in case someone has a better idea for what is causing this, or for when I have more time to look into this in the future.

**Comment by julietchen** [comment]
Hi,
Unfortunately, I'm just reporting the same/a similar bug. Error message at the end. I'm logged into a linux workstation on my company's cluster and using the package Seurat which has a wrapper around Rtsne. My Seurat object is about 6.9Gb and the dataframe itself is around 1.2Gb. When the function runs successfully, it looks like it's using around 9-10Gb of memory. I'm getting the error on data that was normalized slightly differently upstream but is otherwise the same in terms of both the dimensions of the dataframe and the object.size of the dataframe. The function runs perfectly fine on the one dataframe but not the other.

I also see that when I download the data locally onto my mac and run it, the function works fine on the same data that didn't worked when I was running it on the cluster. 

If there's any more information I could provide or tests I can do, I'm happy to, though I will most likely need a bit of guidance. I'm not allowed to share my data.

Thanks!
Julie

Error:
> s <- RunTSNE(s, dims.use = 1:20, do.fast = T)

 *** caught segfault ***
address 0xf2d1, cause 'memory not mapped'

Traceback:
 1: .Call("Rtsne_Rtsne_cpp", PACKAGE = "Rtsne", X, no_dims_in, perplexity_in,     theta_in, verbose, max_iter, distance_precomputed, Y_in,     init, stop_lying_iter_in, mom_switch_iter_in, momentum_in,     final_momentum_in, eta_in, exaggeration_factor_in)
 2: Rtsne_cpp(X, dims, perplexity, theta, verbose, max_iter, is_distance,     Y_init, init, stop_lying_iter, mom_switch_iter, momentum,     final_momentum, eta, exaggeration_factor)
 3: Rtsne.default(as.matrix(data.use), dims = dim_embed, ...)
 4: Rtsne(as.matrix(data.use), dims = dim_embed, ...)
 5: RunTSNE(s, dims.use = 1:20, do.fast = T)
 6: RunTSNE(s, dims.use = 1:20, do.fast = T)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 1
R is aborting now ...
Segmentation fault

**Comment by jkrijthe** [comment]
Thanks for the bug report Julie! Just for completeness: what was the size of the data.frame (number of rows and columns)? I'm still unsure how to debug this as I have been unable to replicate it. Was there any difference in the amount of RAM available on the workstation vs. your Mac?

**Comment by julietchen** [comment]
Hi,

The data.frame is roughly 20k rows by 25k columns. My macbook pro has 16Gb
RAM. The workstation that I log into has at least 64Gb RAM, and I was the
only using it at the time. One of the HPC admins that I was trying to
troubleshoot this with suggested that it was potentially architecture
specific because of this, and that it would be a really difficult problem
to pin down. He also had me qrsh into another node -- I ran R from command
line, and again the function crashed on the one data.frame but ran
perfectly fine on another data.frame with the same dimensions but slightly
different numbers (due to the different upstream normalization).

If I can reproduce the error with some public data set, I'll be sure to
share -- but it seems really random at the moment.

**Comment by s-aibar** [comment]
Hello,

I'm also getting the same error. I had already got it long ago with bigger datasets, but this time it is with a quite small matrix (1592rows x 196columns), so the size doesn't seem to be the (only?) issue. 

I get the error when using a specific seed, but it does work with different seeds, or even with the same seed in different computer... (I can provide you the matrix to see whether you can reproduce it with it... but it might be platform/setup specific...?)

```
Code: 

library(Rtsne)
set.seed(123)
tBinaryMat <- jitter(t(binaryMat), factor=1)
tsne_output <- Rtsne(tBinaryMat, initial_dims=5, perplexity=30)
```

```
Simplified session info: 

R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux ComputeNode release 6.5 (Santiago)

Matrix products: default
BLAS: .../lib64/R/lib/libRblas.so
LAPACK: .../lib64/R/lib/libRlapack.so
locale:
[1] C
other attached packages:
[1] Rtsne_0.13
loaded via a namespace (and not attached):
[1] compiler_3.4.1 Rcpp_0.12.12
```

**Comment by jkrijthe** [comment]
Thanks! It would be great if you could share the script and matrix so that I can attempt to reproduce the problem. Could you send me an email with the details (jkrijthe@gmail.com)?

**Comment by julietchen** [comment]
Hi again,

Changing the seed seems to have fixed the problem as well.

This call (again I'm using Seurat's wrapper around Rtsne) gave me the
segfault/memory not mapped error (the default is k.seed = 1):

> s <- RunTSNE(s, dims.use=1:20, do.fast=T)


But the function seems to be running now with this call:

> s <- RunTSNE(s, dims.use=1:20, do.fast=T, k.seed = 888)


My sessionInfo() if it's helpful:


R version 3.3.2 (2016-10-31)

Platform: x86_64-pc-linux-gnu (64-bit)

Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

attached base packages:

[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:

[1] Seurat_1.4.0.16 cowplot_0.7.0   ggplot2_2.2.1

loaded via a namespace (and not attached):

 [1] mixtools_1.1.0     VGAM_1.0-3         splines_3.3.2      foreach_1.4.3


 [5] gtools_3.5.0       sn_1.5-0           assertthat_0.2.0   stats4_3.3.2


 [9] robustbase_0.92-7  numDeriv_2016.8-1  lattice_0.20-35    quantreg_5.33


[13] glue_1.0.0         RColorBrewer_1.1-2 tclust_1.2-3       minqa_1.2.4


[17] colorspace_1.3-2   fastICA_1.2-1      Matrix_1.2-8       plyr_1.8.4


[21] tsne_0.1-3         SparseM_1.77       caret_6.0-76       mvtnorm_1.0-6


[25] scales_0.4.1       gdata_2.18.0       ranger_0.7.0       Rtsne_0.13


[29] lme4_1.1-13        MatrixModels_0.4-1 tibble_1.3.3       mgcv_1.8-17


[33] car_2.1-4          ROCR_1.0-7         pbapply_1.3-2      nnet_7.3-12


[37] lazyeval_0.2.0     pbkrtest_0.4-7     mnormt_1.5-5
survival_2.41-3

[41] magrittr_1.5       mclust_5.2.3       nlme_3.1-131       MASS_7.3-47


[45] segmented_0.5-1.4  gplots_3.0.1       class_7.3-14       FNN_1.1


[49] tools_3.3.2        trimcluster_0.1-2  stringr_1.2.0      kernlab_0.9-25


[53] munsell_0.4.3      cluster_2.0.6      irlba_2.2.1        fpc_2.1-10


[57] caTools_1.17.1     rlang_0.1.1        grid_3.3.2         nloptr_1.0.4


[61] iterators_1.0.8    igraph_1.0.1       bitops_1.0-6       gtable_0.2.0


[65] ModelMetrics_1.1.0 codetools_0.2-15   lars_1.2           flexmix_2.3-13


[69] reshape2_1.4.2     R6_2.2.1           gridExtra_2.2.1    prabclus_2.2-6


[73] dplyr_0.7.0        KernSmooth_2.23-15 ape_4.1
modeltools_0.2-21

[77] stringi_1.1.5      parallel_3.3.2     Rcpp_0.12.11       DEoptimR_1.0-8


[81] diptest_0.75-7

**Comment by jkrijthe** [comment]
Thanks for the additional information. I have been trying to reproduce @s-aibar 's example, but unfortunately have not managed to do so, so far. So far I have run the example on my Macbook, on a Ubuntu server, a Centos 7 EC2 server and a RHEL 6.5 server on EC2 (to most closely match @s-aibar 's setup) but I have been unable to get a segfault. If anyone runs into this problem again and/or is willing to share their example, please let me know.

**Comment by chriad** [comment]
Hi,

I get the same 'memory not mapped' error as described above. 
I have run the command:

`R -d "valgrind --leak-check=full --show-reachable=yes" -f tsne_test.R |& tee valgrind.txt`

and appended the file valgrind.txt
[valgrind.txt](https://github.com/jkrijthe/Rtsne/files/1482428/valgrind.txt)
I have no idea how to read the output...

My `sessionInfo()` after loading Rtsne:

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

Matrix products: default
BLAS/LAPACK: /usr/prog/OpenBLAS/0.2.8-gompi-1.5.14-NX-LAPACK-3.5.0/lib/libopenblas_nehalemp-r0.2.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rtsne_0.14        ggplot2_2.2.1     lookup_0.0.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13               compiler_3.4.2            
 [3] GenomeInfoDb_1.14.0        plyr_1.8.4                
 [5] XVector_0.18.0             bitops_1.0-6              
 [7] tools_3.4.2                zlibbioc_1.24.0           
 [9] digest_0.6.12              jsonlite_1.5              
[11] memoise_1.1.0              tibble_1.3.4              
[13] gtable_0.2.0               lattice_0.20-35           
[15] rlang_0.1.4                Matrix_1.2-11             
[17] rstudioapi_0.7             DelayedArray_0.4.1        
[19] parallel_3.4.2             GenomeInfoDbData_0.99.1   
[21] withr_2.1.0                httr_1.3.1                
[23] S4Vectors_0.16.0           IRanges_2.12.0            
[25] stats4_3.4.2               grid_3.4.2                
[27] Biobase_2.38.0             R6_2.2.2                  
[29] scales_0.5.0               codetools_0.2-15          
[31] matrixStats_0.52.2-9000    BiocGenerics_0.24.0       
[33] GenomicRanges_1.30.0       SummarizedExperiment_1.8.0
[35] highlite_0.0.0.9000        colorspace_1.3-2          
[37] RCurl_1.95-4.8             lazyeval_0.2.1            
[39] munsell_0.4.3              crayon_1.3.4   
```           
> 

I have also noticed that it does not happen when I use the Rstudio server. However it also seems to be hard to reproduce. Sometime it works and progresses until the tree building stage, sometimes it gets stuck in the "Learning embedding..." stage, confusing...

The space complexity is O(N) for N data points (as I read here https://arxiv.org/pdf/1301.3342.pdf), so having a matrix of double values of dimension 5000x5000 would require 5000*5000*4 bytes = 100Mb? So I would only need a few hundred Mb for a matrix of this input dimension? Is that correct? Then the memory cannot be an issue...

Christian

**Comment by jkrijthe** [comment]
Thanks for the thorough description and for the valgrind output, which, for this run at least, points to a problem when constructing the tree to calculate the perplexities of the input. As you say, it is hard to reproduce and it does not seem to be a lack of memory. The only commonality so far has been the linux distributions used... Unfortunately, I have not been able to reproduce the problem on various machines. Perhaps seeing if running gctorture(TRUE) before the Rtsne call leads to more consistent errors would give a clue whether the randomness of them occurring has something to do with an interaction with the garbage collector.

Also, if you could share (either here or through email) the dataset you are using, I could have another go at tying to reproduce the issue.

**Comment by chriad** [comment]
Here is the script that produces the error. 
[script.zip](https://github.com/jkrijthe/Rtsne/files/1498438/script.zip)

I use batchtools (https://github.com/mllg/batchtools) with a univa grid engine to submit 24 small jobs. When I repeat this process, sometimes all jobs will go through without error but most often 1 or 2 will fail with the above error. The problem is that it appears random which ones fail. I included the gctorture(TRUE) before calling Rtsne but it didn't change the outcome. The jobs all complete successfully with exit status 0. I also tried to change various gird engine parameters but that also didn't change the outcome.

I think it doesn't matter if I submit to the computing cluster or not, the error will occur nontheless (But I havn't tested systematically...). However I do not understand the details of how the scheduler allocates memory to processes and thus have no clue what parameter I would have to change...

Can you point to some other possible causes that I could check?

**Comment by jkrijthe** [comment]
Thanks for trying to better locate the cause of the segfault. Unfortunately, I currently do not have other ideas on how to diagnose this issue further. If others have suggestions or insights into what is going on, I would very much welcome them...

**Comment by touala** [comment]
Hi,

I encounter the same segfault issue pretty often. As describe by @chriad it happened somewhat randomly. I use the following script to produce the error with @chriad dataset (mat.RDS):
```
library(Rtsne)
mat <- readRDS("mat.RDS")
for(i in seq(1,100)){
	print(i)
	x <- Rtsne(X=mat, verbose=TRUE)
}
```
The segfault can happened on the first execution or after 30+ successful ones after "Normalizing input..." message. Same behavior with `gctorture(on=TRUE)`.

I checked that the segfault was similar with valgrind `R -d "valgrind --leak-check=full --show-reachable=yes --track-origins=yes" -f traceback_segfault.R > valgrind_out.txt 2>&1` (see relevant excerpt: [Rtsne_segfault_valgrind.excerpt.txt](https://github.com/jkrijthe/Rtsne/files/1856703/Rtsne_segfault_valgrind.excerpt.txt)). I have other errors reported by valgrind but it seems to be false positive [caused by mkl library](https://stackoverflow.com/questions/28339777/valgrind-reports-mkls-dsyev-memory-leak) but it might be important.

Interestingly, setting a seeds seems to make the behavior more predictable. The following code block segfault on the 3rd iteration after "Normalizing input..." message. Note that I tested it on three nodes only (2 Intel, 1 AMD), and it do not segfault on OSX or Ubuntu in AWS.

```
library(Rtsne)
mat <- readRDS("mat.RDS")
set.seed(2)
for(i in seq(1,100)){
	print(i)
	x <- Rtsne(X=mat, verbose=TRUE)
}
```
I also tested with your example usage (iris dataset) and it segfault at iteration 1 for seed=42 and iteration 3 for seed=1 but when I run the code with valgrind segfault iteration changed... 

I run the code on our cluster in interactive mode (not jobs), memory should not be an issue (~500GB), and it's a different distribution (e.g. CentOS). I don't use RStudio.

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.2 (Final)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] colorout_1.1-2 setwidth_1.0-4
```

I'm not sure how to diagnose the issue further. I suppose it can come from improper compilation. Here is R output from `install.packages("Rtsne")`. Is there something suspicious?
```
g++ -I/hpc/packages/node01/R/3.3.1/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/hpc/users/user01/.Rlib/Rcpp/include"   -fpic  -O3 -fopenmp  -c RcppExports.cpp -o RcppExports.o
g++ -I/hpc/packages/node01/R/3.3.1/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/hpc/users/user01/.Rlib/Rcpp/include"   -fpic  -O3 -fopenmp  -c Rtsne.cpp -o Rtsne.o
gcc -std=gnu99 -I/hpc/packages/node01/R/3.3.1/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/hpc/users/user01/.Rlib/Rcpp/include"   -fpic  -O3 -fopenmp  -c init.c -o init.o
g++ -I/hpc/packages/node01/R/3.3.1/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/hpc/users/user01/.Rlib/Rcpp/include"   -fpic  -O3 -fopenmp  -c sptree.cpp -o sptree.o
g++ -I/hpc/packages/node01/R/3.3.1/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/hpc/users/user01/.Rlib/Rcpp/include"   -fpic  -O3 -fopenmp  -c tsne.cpp -o tsne.o
g++ -shared -L/hpc/packages/node01/R/3.3.1/lib64/R/lib -L/usr/local/lib64 -o Rtsne.so RcppExports.o Rtsne.o init.o sptree.o tsne.o -lmkl_gf_lp64 -lmkl_gnu_thread -lmkl_core -liomp5 -lpthread -lgfortran -lm -lgomp -lquadmath -lpthread -L/hpc/packages/node01/R/3.3.1/lib64/R/lib -lR
```
 We don't use the macro `LAPACK_LIBS` by default. I added it to my `~/.R/Makevars` and reinstall but the segfault still occur at the same iteration. gcc version is `4.8.2`.

**Comment by jkrijthe** [comment]
Thanks for looking into this. Just to clarify: do all three nodes that you tested on run the same version of CentOS? And to answer your question: I do not see anything suspicious at first glance, these all seem like reasonable settings to me.

**Comment by touala** [comment]
Yes `sessionInfo()` gave the same CentOS version.

**Comment by jkrijthe** [comment]
Thanks, so far, it seems the commonality is that this only occurs on RHEL/Centos, and the segfault occurs during the construction of the Vantage Point tree, in vptree.h. So I would start debugging the the euclidean_distance function in that file, but unfortunately, I do not have access to a Centos machine, and I did not get similar behaviour when trying to reproduce it on Centos on AWS either, when I tried this earlier.

**Comment by touala** [comment]
FYI, I also tried to replicate the bug on a fresh CentOS 6.9 install in a VM but the package works properly.

**Comment by touala** [comment]
Good news! Our HPC administrator took a look at this issue and noticed that the code failed after different number of cycles depending on the compiler version. He reinstalled your package using gcc `7.3.0` instead of our default `4.8.2`. I tested the reproducible script with a couple of seeds as well as a dozen others large matrices with success.

**Comment by jkrijthe** [comment]
That is good news! Thank you for testing this. Still a mystery to me what causes this, but at least using a different compiler may offer a workaround.

**Comment by jkrijthe** [comment]
Hoping the updated compiler version resolved this issue. If not, we can reopen the issue.
