### ISSUE TITLE
LICENSE mismatch

### ISSUE THREAD

**Issue by detrout** [jkrijthe/Rtsne#28]
Hello,

You list a license of BSD-3-Clause on your R CRAN page
https://cran.rstudio.com/web/packages/Rtsne/index.html

But src/tsne.h lists the deprecated BSD 4 clause license that causes complications with GPL licensed software. https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_(original_%22BSD_License%22)

Is there a chance you could make everything consistently BSD-3-clause? or updated the metadata at CRAN?

**Comment by jkrijthe** [comment]
Thanks for finding this discrepancy. Indeed I think the license should be BSD-4 for the C++ code included in the package. Although I would want to, I'm afraid I can not change everything to BSD-3 since the C++ files included are (as you pointed out) licensed under BSD-4. Perhaps Laurens van der Maaten, the original author of those files (https://github.com/lvdmaaten/bhtsne) would be willing to change this.

**Comment by jkrijthe** [comment]
Thanks again, and sorry this took so long. The license information has been clarified in the repository and on CRAN to reflect the BSD-3/BSD-4 mix. Unfortunately, I cannot change everything to BSD-3 unless the upstream C++ code would switch to BSD-3.

**Comment by detrout** [comment]
Ok. Thank you for looking into it and letting me know the results.
