### ISSUE TITLE
Maximum perplexity constraint

### ISSUE THREAD

**Issue by guilhermesena** [jkrijthe/Rtsne#29]
Rtsne limits the maximum perplexity value (N-1)/3, where N is the number of data points. Is there a reasoning behind this constraint? I can't seem to justify it based on the theorey in the paeprs so I was curious of potential issues of increasing it above this threshold.

Thank you in advance!

**Comment by jkrijthe** [comment]
The constraint is copied from the underlying implementation the package is based on (https://github.com/lvdmaaten/bhtsne/). I think it comes from the sparse approximation used only considering the 3*perplexity nearest neighbours, and given that any object has N-1 neighbours, it can not consider more. I agree that there are probably more elegant ways to implement this, especially when exact t-sne is used instead of the approximation, but I have not looked into it. Hope this helps!

**Comment by guilhermesena** [comment]
that definitely clears it up. Thank you very much!
