### ISSUE TITLE
Wish: prevent deteriorating between iterations

### ISSUE THREAD

**Issue by ugroempi** [jkrijthe/Rtsne#33]
I am surprised that Rtsne does not improve (or stay the same) from iteration to iteration. Increasing the number of iterations eventually cycles between solutions of similar quality, but does not keep the best ones (e.g. for `Rtsne(swiss, perplexity=15, max_iter=1000, verbose=TRUE)`). Couldn't that be changed?

Best, Ulrike

**Comment by jkrijthe** [comment]
Indeed, the algorithm is defined as running a certain number of gradient descent steps (max_iter is a misnomer since it is not the max but the exact number of iterations), and does not take into account the value of the objective function. 

Although it is certainly possible to implement some scheme that saves the embedding with the lowest objective function value during gradient descent, there are several choices involved on how this could be done. For instance, one would need to define how often the objective function should be evaluated (by default it is evaluated every 50 iterations). Anyway, I think it would have to be an optional setting to keep older code reproducible.

I currently have no plans to implement this, but I will keep the issue open in case anyone is interested in implementing this feature.

**Comment by jkrijthe** [comment]
Thanks again for the request. To stay consistent with the original implementation, I have no plans to include this at present, but might reconsider at some point.
