### ISSUE TITLE
Failed to load the distance matrix from aligned DNA sequences 

### ISSUE THREAD

**Issue by yeli7068** [jkrijthe/Rtsne#44]
Hi,

Thanks for your works. I am trying to use Rtsne to analysis the distance matrix from aligned DNA sequences as attached.

The error reported is 

> Error in .check_tsne_params(nrow(X), dims = dims, perplexity = perplexity,  : 
  perplexity is too large for the number of samples

Here is the code: 
`
library(ape)
library(Rtsne)

dna <- read.dna(file = "Norovirus.aligned.txt", format = 'fasta')
D <- dist.dna(dna, model = "TN93")
D_uniq <- unique(D)
dna.tsne <- Rtsne(as.matrix(normalize_input(as.matrix(D_uniq))))

or
dna <- read.dna(file = "Norovirus.aligned.txt", format = 'fasta')
D <- dist.dna(dna, model = "TN93")
dna.tsne <- Rtsne(as.matrix(D), is_distance = TRUE)
`

[Norovirus.aligned.txt](https://github.com/jkrijthe/Rtsne/files/2754019/Norovirus.aligned.txt)

R: 3.5.1
OS: MacOS 10.13.6

Any helps from you will be highly appreciated!

Cheers!

**Comment by jkrijthe** [comment]
If I understand it correctly, you have a distance matrix containing distances between 10 objects. Your second code example would then be most appropriate, since you only have a distance matrix. The perplexity error is thrown since the default perplexity (30) is too high for your dataset: since there are only 10 objects, you can not look at the 30 nearest neighbours. So you should set the perplexity to a lower value (using the perplexity argument, see documentation for details) to get an embedding.
