### ISSUE TITLE
Multiple tsne plots comparable

### ISSUE THREAD

**Issue by yilinwu123** [jkrijthe/Rtsne#53]
Dear developer:

I am interested using Rtsne for my research project. I would like to do research about the effects of different normalization methods  on clustering using my high-dimensional dataset. I first normalized the original dataset using different normalization methods. Then, I showed several tsne plots (one plot for each normalized dataset), compared these plots and checked which normalization method is helpful for clustering algorithm. May I ask:

Are the x and y axes comparable across the plots for different normalized data? Could I compare these plots directly (e.g. the plot which shows clusters obviously means the dataset is well separated into each cluster than other plots). Here is my code to generate multiple tsne plots:

tsne_fit<-normalized data%>%Rtsne()
tsne_df<- tsne_fit$Y%>%as.data.frame()%>%rename(tSNE1='V1',tSNE2='V2')%>%mutate(ID=substr(rownames(normalized data), 7, 7))
tsne_df%>%ggplot(aes(x=tSNE1,y=tSNE2,color=ID))+geom_point()

Thank you so much for your help!

**Comment by SamGG** [comment]
Not being the developer.
The tSNE computation are stochastic as you probably know.
Because you are not comparing the effect of normalization on tSNE map, but just visualising the output of clustering IIUC, I would compute only once tSNE, then display all clusterings using that unique tSNE map.
Alternatively, you could initialize tSNE with the 2 first PCA coordinates, but this bypasses the 1 phase of tSNE IIRC, so you will have to the 2 phases process by hand.
Let us know about your findings.

**Comment by jkrijthe** [comment]
If I understand correctly, the code you showed is just your example of how you generate the plot for a single normalization (in the normalized data object). And then you do this for each of the normalization methods your are interested in? If you are going to compare them, some thoughts:
1. As Samuel points out, tsne is stochastic, so rerunning the embedding with a different seed will give different results, even if you do not change the normalization
2. The x and y "components" of tsne have no inherent meaning, it is only the distance between objects that the embedding cares about (so maps can be arbitrarily rotated or flipped, and still represent the "same" embedding). So the x and y axes are not comparable across embeddings.

**Comment by yilinwu123** [comment]
Hello Jesse and Samuel

Thanks a lot for your quick replies and suggestions. Yes, the code is for generating a plot for a single normalized data and I do this for each of the normalization method. 

1. Since tsne is stochastic, could I set the same 'seed' every time before I generate each plot of the normalization method to compare the results across plots?
2. I read some papers about comparing different normalization methods on single-cell RNA sequencing data. They visualized the clustering structure of different normalized data using multiple tsne plots and found which normalization method could separate the points well. Since x and y axes are not comparable, I am considering whether it is reasonable to compare how well data points are separated into clusters across multiple tsne plots instead of focusing on the absolute values of x and y axes.

Thanks again for your help!

**Comment by SamGG** [comment]
1. setting the same seed is a necessary step, but since data are not the same, the result will be different, unless the normalisation multiplies all the values by a constant. If you really intend to compare the clustering, the tSNE has to be computed once, but you can choose the one that you prefer. How would you choose it? That's the question. I think that changes will be minor.
2. If you intend to compare the normalisation on tSNE and clustering, that is easy IMHO. The observation by eye is a quite subjective criterium, but I don't think one cirterium solves this issue. Even if you know the truth (e.g. simulated dataset), setting a criterium sounds a difficult task to me. So if it's about real data, with not really well separated clusters, good luck.
Best.

**Comment by yilinwu123** [comment]
> 1. setting the same seed is a necessary step, but since data are not the same, the result will be different, unless the normalisation multiplies all the values by a constant. If you really intend to compare the clustering, the tSNE has to be computed once, but you can choose the one that you prefer. How would you choose it? That's the question. I think that changes will be minor.
> 2. If you intend to compare the normalisation on tSNE and clustering, that is easy IMHO. The observation by eye is a quite subjective criterium, but I don't think one cirterium solves this issue. Even if you know the truth (e.g. simulated dataset), setting a criterium sounds a difficult task to me. So if it's about real data, with not really well separated clusters, good luck.
>    Best.

Hi Samuel:

Thanks so much for your suggestions. They are very helpful!
