### ISSUE TITLE
distance is squared within the Rtsne function when theta set to 0 and distance matrix provided

### ISSUE THREAD

**Issue by lcougnaud** [jkrijthe/Rtsne#7]
When a distance matrix is provided as input, I have noticed that the distance is squared within the Rtsne function before passing it to the Rtsne_cpp function, when the exact tsne is used:
```
if(is_distance & theta == 0) X <- X^2
```
Is there a specific reason to do so? Is it to have a quite equivalent approach when a raw data matrix is provided, as the data is transformed with an squared Euclidean distance by default (in the C++ code)? If so, why is it done only when the tsne is exact (theta == 0)?

Thanks in advance for your time, this is a very useful package.

**Comment by jkrijthe** [comment]
Thanks for bringing this to my attention. The reason I only did this for theta==0.0 is that the underlying implementation does not seem to do the squaring initially when theta!=0.0 when you input a data matrix. I had assumed the distances were squared later in a different part of the code, but upon closer inspection I am not able to find whether this is in fact true. I will look into this and report back when I know more.

**Comment by jkrijthe** [comment]
Thanks again for submitting this question. While looking further into why I decided to only square the distances in the R code for the exact TSNE algorithm, I ran into a bug in the C++ code, that caused the distances to not be squared in the calculation of the pairwise similarities. This has now been fixed both here and in the original code at https://github.com/lvdmaaten/bhtsne.

Hope this answers your question.

**Comment by lcougnaud** [comment]
Thanks for your quick feedback on this question.
In general, do you know if there any reason for the fact that the matrix should be squared as input for the tsne?
We would be very interested to apply your function with some less conventional 'distance-like' measures, especially using the Pearson correlation to estimate similarity (in fact using 1 - correlation as 'distance matrix'). In this specific case, we wouldn't like to use squared distance values.
Is there a possibility to include a parameter to specify if the distance should or should not be squared internally in the function?
Many thanks in advance

**Comment by jkrijthe** [comment]
The squaring is merely done because in the original t-SNE algorithm, the distances are only used in the calculation of the Gaussian perplexity, where the distances are squared anyway. So if you want to use t-SNE with a different distance measure, such as 1-cor, this should work as expected (in other words, if you would turn the squaring off, as you suggest, you would get the t-SNE map of the \sqrt(1-cor(x,y)) distance measure).

Do note that using a non-metric distance measure potentially causes a problem in the approximation done in the Barnes-Hut t-SNE algorithm. I have used 1-cor as distance in the past and it gave useful visualizations, even though a requirement of the approximation is that the distance measure is metric.

Hope this answers your question.

**Comment by lcougnaud** [comment]
Many thanks for your response, this answers my question indeed.
